# Generated by Django 4.0.9 on 2023-02-26 15:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('busses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_departure', models.DateTimeField()),
                ('date_arrival', models.DateTimeField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_assignment', to='busses.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('seat_number', models.IntegerField()),
                ('bus_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='busses.busassignment')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='date_arrival',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='date_departure',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='destination',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ScheduleAssigment',
        ),
        migrations.AddField(
            model_name='busassignment',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_assignment', to='busses.driver'),
        ),
        migrations.AddField(
            model_name='busassignment',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_assignment', to='busses.route'),
        ),
    ]
