# Generated by Django 4.0.9 on 2023-02-26 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busassignment',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='busassignment',
            name='departure_date',
        ),
    ]
