# Generated by Django 4.0.9 on 2023-02-28 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busses', '0002_remove_busassignment_arrival_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trayecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='bus_assignment',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='bus',
            name='capacidad',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='bus',
            name='numero_placa',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='BusAssignment',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.AddField(
            model_name='bus',
            name='chofer',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='busses.chofer'),
        ),
    ]
