# Generated by Django 4.0.9 on 2023-03-02 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busses', '0003_chofer_trayecto_remove_passenger_bus_assignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_llegada', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='bus',
            name='capacidad',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('asiento', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('corrida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busses.corrida')),
            ],
        ),
        migrations.AddField(
            model_name='corrida',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busses.bus'),
        ),
        migrations.AddField(
            model_name='corrida',
            name='trayecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busses.trayecto'),
        ),
    ]
