# Generated by Django 4.0.9 on 2023-03-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busses', '0004_corrida_alter_bus_capacidad_pasajero_corrida_bus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corrida',
            name='capacidad',
            field=models.SmallIntegerField(default=0),
        ),
    ]
