# Generated by Django 4.0.9 on 2023-03-02 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busses', '0005_corrida_capacidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(unique=True)),
                ('estado', models.CharField(max_length=20)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busses.bus')),
            ],
        ),
        migrations.RemoveField(
            model_name='corrida',
            name='capacidad',
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='busses.asiento')),
                ('corrida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busses.corrida')),
                ('pasajero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='busses.pasajero')),
            ],
        ),
    ]
