# Generated by Django 4.0.9 on 2023-03-03 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busses', '0006_asiento_remove_corrida_capacidad_boleto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasajero',
            name='asiento',
        ),
        migrations.RemoveField(
            model_name='pasajero',
            name='corrida',
        ),
    ]
