# Generated by Django 4.0.9 on 2023-03-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busses', '0007_remove_pasajero_asiento_remove_pasajero_corrida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asiento',
            name='numero',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
