# Generated by Django 4.0.9 on 2023-03-08 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busses', '0008_alter_asiento_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='pasajero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busses.pasajero'),
        ),
    ]
